version: '3.8'

services:
  backend:
    build:
      context: ./AEJ_03_be
      dockerfile: Dockerfile
    image: aej03-be:latest
    environment:
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build:
      context: ./AEJ_03_fe
      dockerfile: Dockerfile
      args:
        APIURL: "http://localhost:8080/api/aiome"
    image: aej03-fe:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always