spring:
  application:
    name: AIOME
  datasource:
    url: jdbc:postgresql://ep-lucky-band-acmf0c65-pooler.sa-east-1.aws.neon.tech:5432/apis?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_5hATvbrqKD9o
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  ai:
    copilot:
      api-key: 70d2b19518msh27c0dc634d2bfd1p1dea1djsncacae4126f0f
      api-host: copilot11.p.rapidapi.com
      api-url: https://copilot11.p.rapidapi.com/
    gemini:
      api-key: AIzaSyAWvrzXRCrTrP5LVQB4cDd5_ACvkqRh_vw
      api-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent

server:
  port: 8086

# CORS Configuration
cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: false
  packages-to-scan: edu.pe.vallegrande.AIOME.controller
  
# Logging (opcional, para debug)
logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: DEBUG